key_id: "changeme"
node_provider:
  default: "wss://ws.azero.dev:443"
  Azero: "wss://ws.azero.dev:443"
  AzeroTest: "wss://ws.test.azero.dev:443"

chain_id:
  default: 0
  Azero: 0
  AzeroTest: 1
ext_hostname: "http://localhost:8081"
frontend_host: "http://localhost:8081"
#eddsa_pem: "-----BEGIN PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEIOKlIljKAZAW2V8x4Vq+Xc9k6IVQplhg1nyeoaj245Zp\n-----END PRIVATE KEY-----"
rsa_pem_file: "private_rsa.pem"
port: 8081
frontend_dir: dist/
